# scatter_
`A.scatter_(dim, index, src)`将src中的数据按照index的索引，以dim的方向填进A中

In [3]:
import torch
x = torch.rand(2, 5)
print(x)

tensor([[0.4019, 0.2845, 0.1323, 0.0027, 0.6440],
        [0.6203, 0.7380, 0.5259, 0.3852, 0.0768]])


In [17]:
# index和src的维度大小相同
# dim=0的情况:index[i][j]=y表示把src[i][j]填到torch.zeros(3, 5)第j列的第y行
# 参数里写关键字参数时src必须是Tensor
torch.zeros(3, 5).scatter_(dim=0, index=torch.tensor([[0, 1, 1, 2, 0], [1, 1, 1, 2, 0]], dtype=torch.long), src=x)

tensor([[0.4019, 0.0000, 0.0000, 0.0000, 0.0768],
        [0.6203, 0.7380, 0.5259, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.3852, 0.0000]])

In [28]:
# 参数里不写关键字参数时src可以是标量
torch.zeros(2, 4).scatter_(1, torch.tensor([[0], [2]], dtype=torch.long), 999)

tensor([[999.,   0.,   0.,   0.],
        [  0.,   0., 999.,   0.]])

scatter_一般用于one-hot编码

In [37]:
def one_hot(label, depth=10):
    label = torch.tensor(label, dtype=torch.long).view(-1, 1)
    return torch.zeros(label.shape[0], depth).scatter_(1, label, 1)  # 第一维是dim，最后一维是src

label = [0, 1, 2, 3, 4, 5]
print(one_hot(label, 10))

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])


# torch.gather
`torch.gather(input, dim, index)`沿dim指定的轴收集值  
input和index必须在dim之外的轴具有相同的维度，index是需要收集的元素的下标  
参数：
+ `input(Tensor)`
+ `dim(int)`
+ `index(LongTensor)`

返回值维度:与index维度相同

In [33]:
a =torch.rand(2, 4)
index_1 = torch.tensor([[0, 0], [1, 2]], dtype=torch.long)
index_2 = torch.tensor([[0, 1, 1]], dtype=torch.long)
print(a)
print(torch.gather(a, dim=1, index=index_1))
print(torch.gather(a, dim=0, index=index_2))

tensor([[0.9953, 0.7549, 0.6824, 0.1374],
        [0.5895, 0.0741, 0.2023, 0.1271]])
tensor([[0.9953, 0.9953],
        [0.0741, 0.2023]])
tensor([[0.9953, 0.0741, 0.2023]])


# torch.index_select
`torch.index_select(input, dim, index)`返回input沿着dim的在index索引的值  
参数：  
+ `input(Tensor)`
+ `dim(int)`
+ `index(IntTensor或LongTensor)-1D`  


In [35]:
x = torch.randn(3, 4)
index = torch.tensor([0, 2], dtype=torch.long)
print(x)
print(torch.index_select(x, dim=0, index=index))  # 选第0行和第2行
print(torch.index_select(x, dim=1, index=index))  # 选第0列和第2列

tensor([[ 0.2119,  0.1211, -1.8723, -0.1723],
        [-1.1398, -0.6651, -0.3263,  0.1650],
        [-0.4939,  0.2822, -0.4143,  0.6353]])
tensor([[ 0.2119,  0.1211, -1.8723, -0.1723],
        [-0.4939,  0.2822, -0.4143,  0.6353]])
tensor([[ 0.2119, -1.8723],
        [-1.1398, -0.3263],
        [-0.4939, -0.4143]])


# torch.masked_select
`torch.masked_select(input, mask)`根据mask中的bool值，选择input中的元素，返回1-DTensor  
参数：
+ `input(Tensor)`
+ `mask(torch.bool)`

In [47]:
x = torch.randn(3, 4)
mask = torch.tensor(x>0, dtype=torch.bool)
print(x)
print(mask)
print(torch.masked_select(x, mask))


tensor([[-0.9987,  0.4365,  0.6507, -0.8925],
        [ 0.1953, -0.2860,  0.2485,  0.4445],
        [ 0.2678,  0.1746, -0.2951, -0.9962]])
tensor([[False,  True,  True, False],
        [ True, False,  True,  True],
        [ True,  True, False, False]])
tensor([0.4365, 0.6507, 0.1953, 0.2485, 0.4445, 0.2678, 0.1746])


<ipython-input-47-d04bc8545e96>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = torch.tensor(xx>0, dtype=torch.bool)
