# 基本数据类型
+ torch.float32(torch.float)
+ torch.float64(torch.double)
+ torch.int32(torch.int)
+ torch.int64(torch.long)
+ torch.bool

In [1]:
import torch
a = torch.tensor([1, 2, 3], dtype=torch.long)
print(a, a.dtype)
a = torch.tensor([1, 2, 3], dtype=torch.float)
print(a, a.dtype)
a = torch.tensor([1, 2, 3], dtype=torch.bool)
print(a, a.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32
tensor([True, True, True]) torch.bool


`torch.rand`生成[0, 1)之间的均匀分布  
`torch.randn`生成标准正态分布

In [2]:
a = torch.rand(2, 3)
b = torch.randn(3, 1)
print(a)
print(a.shape)
print(b)
print(b.shape)

tensor([[0.2509, 0.9394, 0.2846],
        [0.3122, 0.4418, 0.0227]])
torch.Size([2, 3])
tensor([[ 0.6012],
        [-0.1440],
        [ 0.4867]])
torch.Size([3, 1])


# 创建tensor 
`torch.from_numpy(ndarray)`是浅拷贝  
`torch.as_tensor(data, dtype=None, device=None)`:  
+ 如果data已经是tensor且dtype和device与参数相同，则创建的tensor与data共享内存
+ 如果data是narray，且dtype对应，device是cpu，则创建的tensor与data共享内存
+ 否则是深拷贝

In [13]:
import numpy as np
a = np.array([1, 2, 3])
b = torch.from_numpy(a)
print(a)
a = np.array([1, 2, 3])
b = torch.as_tensor(a, device=torch.device('cpu'))
print(a)

[1 2 3]
[1 2 3]


直接创建  
`torch.Tensor`==`torch.FloatTensor`  
**注意：**
+ `torch.tensor(4)`创建一个值为4的标量tensor
+ `torch.Tensor(4)`创建长度为4，每个值是0.0的1维tensor

In [14]:
a = torch.Tensor([[1, 2], [3, 4]])
b = torch.FloatTensor([[1, 2], [3, 4]])
print(a.dtype)
print(b.dtype)

torch.float32
torch.float32


`torch.tensor(data, dtype=None, device=None, requires_grad=False) `是对data的深拷贝  
+ 如果只是想改变一个Tensor数据的`requires_grad`标志，使用`requires_grad_()`或者`detach()`来避免深拷贝  
+ 当x是tensor时`torch.tensor(x)` == `x.clone().detach()`
+ `torch.tensor(x, reauires_grad=True)` == `x.clone().detach().requires_grad_(True)`

In [19]:
a = torch.tensor([1, 2, 3], dtype=torch.float)
print(a)
b = a.clone().detach()  # 等价于torch.tensor(a)
print(b)
b[0] = -1
print(a)
print(b)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([-1.,  2.,  3.])


`torch.full`  
`torch.full(size, full_value)`返回值的dtype由full_value的值决定

In [8]:
a = torch.full((2, 3), 7)
b = torch.full((2, 3), 7.7)
print(a.dtype)
print(b.dtype)
print(b)

torch.int64
torch.float32
tensor([[7.7000, 7.7000, 7.7000],
        [7.7000, 7.7000, 7.7000]])


`torch.arange`

In [22]:
a = torch.arange(1, 5)
b = torch.arange(1, 5, step=1.5)
print(a, a.dtype)
print(b, b.dtype)

tensor([1, 2, 3, 4]) torch.int64
tensor([1.0000, 2.5000, 4.0000]) torch.float32
