# view/reshape
## view  
**view操作要求tensor在内存中是连续存储的**，在进行了transpose、permute操作之后tensor不连续，需要使用contiguous得到一个连续的copy，之后再进view操作  
## reshape
**reshape函数相当于tensor.contiguous().view()**，省去了对tensor进行view操作前的contiguous操作

In [2]:
import torch
a = torch.rand(3, 4)
b = a.transpose(0, 1)
b.is_contiguous()  # False
print(a.reshape(2, 6))
print(a.view(2, 6))
print(b.reshape(2, 6))
print(b.contiguous().view(2, 6))
# print(b.view(2, 6))报错

tensor([[0.8238, 0.2714, 0.1760, 0.6312, 0.7975, 0.4702],
        [0.7563, 0.7784, 0.5535, 0.7110, 0.6299, 0.8340]])
tensor([[0.8238, 0.2714, 0.1760, 0.6312, 0.7975, 0.4702],
        [0.7563, 0.7784, 0.5535, 0.7110, 0.6299, 0.8340]])
tensor([[0.8238, 0.7975, 0.5535, 0.2714, 0.4702, 0.7110],
        [0.1760, 0.7563, 0.6299, 0.6312, 0.7784, 0.8340]])
tensor([[0.8238, 0.7975, 0.5535, 0.2714, 0.4702, 0.7110],
        [0.1760, 0.7563, 0.6299, 0.6312, 0.7784, 0.8340]])


# unsqueeze/squeeze
## unsqueeze
+ **作用**：维度扩展
+ **注意**：返回的tensor和输入的tensor共享内存，改变其中一个的内容会改变另一个  
## squeeze
+ **作用**：维度压缩，比如输入tensor的形状是$A\times 1\times B\times 1\times C$，返回的tensor形状是$A\times B\times C$，当给定dim时，挤压操作只会发生在指定的dim上
+ **注意**：返回的tensor和输入的tensor共享内存，改变其中一个的内容会改变另一个

In [5]:
import torch
a = torch.rand(1, 3, 1, 4)
print(a.squeeze().shape)
print(a.squeeze(dim=0).shape)
print(a.unsqueeze(dim=4).shape)

torch.Size([3, 4])
torch.Size([3, 1, 4])
torch.Size([1, 3, 1, 4, 1])


# expand/repeat
## Tensor.expand(*size)->Tensor
+ **作用**：扩展tensor，size的维度要等于原tensor维度
+ **注意**：**浅拷贝，只能扩展维度为1的那一维**，当传入参数为-1时那一维不做扩展  
## Tensor.repeat(*size)->Tensor
+ **作用**：扩展tensor，size的维度要大于等于原tensor维度，size[i]表示把对应tensor的维度扩展为**多少倍**
+ **注意**：**深拷贝**

In [6]:
a = torch.tensor([[1, 2, 3]])
print(a.expand(3, -1))
print(a.expand(3, 3))  # 等价与上面一条
print(a.repeat(3, 1))
print(a.repeat(2, 3, 2).shape)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
torch.Size([2, 3, 6])


# transpose/permute
## Tensor.transpose(dim0, dim1) → Tensor
+ **作用**：交换两个维度
+ **注意**：浅拷贝，会使原来contiguous的tensor变得不contiguous  
## Tensor.permute(*dims) → Tensor
+ **作用**：交换tensor的维度，dim的维度等于原tensor的维度大小，dim[0]表示变换后的tensor的第一维是原tensor的第几维
+ **注意**：浅拷贝，会使原来contiguous的tensor变得不contiguous


In [9]:
a = torch.rand(2, 3, 4)
b = a.transpose(1, 2)
c = a.permute(2, 1, 0)
print(b.shape)
print(c.shape)
print(b.is_contiguous())

torch.Size([2, 4, 3])
torch.Size([4, 3, 2])
False
