# + - * /
`+ - * /`运算  
等价于`torch.add torch.mul torch.sub torch.div`  
元素级别的运算

In [1]:
import torch
a = torch.ones(2, 2)
b = torch.full((2, 2), 3)
print(a * b)
print(torch.mul(a, b))

tensor([[3., 3.],
        [3., 3.]])
tensor([[3., 3.],
        [3., 3.]])


# mm/bmm/matmul
## torch.mm(input, mat2, *, out=None) → Tensor
+ **作用：** 矩阵相乘
+ **注意：** 只支持2D-tensor的矩阵相乘，并且只支持torch.float32类型

## torch.bmm(input, mat2, out=None) → Tensor
+ **作用：** 一个batch的矩阵相乘
+ **注意：** 只支持3D-tensor的矩阵相乘，并且只支持torch.float32类型

## torch.matmul(input, other, out=None) → Tensor
+ **作用：** 高维矩阵相乘
+ **注意：** 只支持torch.float32类型，@是其重载运算符号

In [5]:
a = torch.rand(2, 3)
b = torch.rand(3, 10)
print(torch.mm(a, b).shape)
a = torch.rand(128, 2, 3)
b = torch.rand(128, 3, 1)
print(torch.bmm(a, b).shape)
a = torch.rand(128, 64, 5, 4)
b = torch.rand(128, 64, 4, 9)
c = torch.matmul(a, b)
d = a @ b
print(c.shape)
print(torch.all(c == d))  # torch.all判断是不是全是True

torch.Size([2, 10])
torch.Size([128, 2, 1])
torch.Size([128, 64, 5, 9])
tensor(True)


# pow/sqrt
`Tensor.pow(n)`表示元素级别的n次方，与`**`运算等价  
`Tensor.sqrt()`元素级别的平方根

# exp/log
+ `torch.exp(a)`等价于`a.exp()`，表示e的a次方
+ `log(a)`表示ln(a)
+ `log2(a)`、`log10(a)`

In [7]:
a = torch.ones(2, 2)
b = a.exp()
print(b)
print(torch.log(b))
print(b.log())

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


# floor/ceil
+ `torch.floor(Tensor)` == `Tensor.floor()`向下取整
+ `torch.ceil(Tensor)` == `Tensor.ceil()`向上取整

# clamp
## torch.clamp(input, min=None, max=None, out=None) → Tensor
+ **作用：** 将input裁剪至[min, max]的范围内

In [10]:
a = torch.randn(3, 3)
print(a)
print(torch.clamp(a, min=-0.5, max=0.5))

tensor([[-0.6658,  0.5922,  0.0430],
        [ 0.0350, -0.3757, -0.6489],
        [-0.4853, -1.1734,  0.0569]])
tensor([[-0.5000,  0.5000,  0.0430],
        [ 0.0350, -0.3757, -0.5000],
        [-0.4853, -0.5000,  0.0569]])
